--Made to not mingle with the main defines.lua file

NDefines.NMilitary.SLACKEN_AP_DROP = 0.025
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 0.5
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_BASE = 0
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_RANGE = 0
NDefines.NEconomy.TRADE_ADDED_VALUE_MODIFER = 0
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = 0
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 5,