--Made to not mingle with the main defines.lua file

NDefines.NMilitary.SLACKEN_AP_DROP = 0.025
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 0.5
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_BASE = 5
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_RANGE = 11
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 5
NDefines.NEconomy.TRADE_ADDED_VALUE_MODIFER = 0.02
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = 0
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 5475
NDefines.NMilitary.LEADER_MAX_PIPS = 7
NDefines.Nmilitary.MERCENARY_COMPANY_MANPOWER_PER_REGIMENT = 0.75