--Made to not mingle with the main defines.lua file

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_BASE = 5
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_RANGE = 11
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 5
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 5475
NDefines.NMilitary.LEADER_MAX_PIPS = 7
NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_PER_REGIMENT = 1.25
NDefines.NMilitary.MERCENARY_REINFORCE_COST_MULTIPLIER = 1.0
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.7
NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NEconomy.MINIMUM_INTERESTS = 2.0
NDefines.NCountry.PS_ASSAULT = 5
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 50
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 50
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 5450
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25
NDefines.NCountry.ABANDON_CORE_PRESTIGE = -0.0
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = -0.0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.RAZE_PROVINCE_DEVELOPMENT_DECREASE = 0.25
NDefines.NCountry.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 10.0